apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: agent-warden-portal-secrets
  namespace: agent-warden-system
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "63e88f9f-8d2c-4b88-b29f-ddf2b6728c66"
    keyvaultName: "kv-plat-awarden-dev"
    tenantId: "dab94ed2-4cee-4b36-b007-6618f570b4a3"
    objects: |
      array:
        - |
          objectName: entra-portal-client-id
          objectType: secret
        - |
          objectName: entra-portal-tenant-id
          objectType: secret
        - |
          objectName: mcp-auth-token
          objectType: secret
  secretObjects:
    - secretName: agent-warden-portal-secrets
      type: Opaque
      data:
        - objectName: entra-portal-client-id
          key: PUBLIC_ENTRA_CLIENT_ID
        - objectName: entra-portal-tenant-id
          key: PUBLIC_ENTRA_TENANT_ID
        - objectName: mcp-auth-token
          key: MCP_AUTH_TOKEN
